config/routes.rb
Rails.application.routes.draw do

  get 'onboarding_question/show'
  devise_for :users, controllers: {registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks'}
  get 'profile', to: 'profile#show'
  get 'impact', to: 'impact#index'
  root to: 'my_fishes#show'

  # CHALLENGES

  resources :challenges, only: [:index, :show] do
    resources :my_challenges, only: [:create]
    resources :questions, only: [:show]
    member do
      get 'completed'
      get 'ongoing'
    end
  end

  get 'my_challenges/ongoing', to: 'my_challenges#ongoing', as: :ongoing_challenges
  get 'my_challenges/completed', to: 'my_challenges#completed', as: :completed_challenges

  #ONBOARDING
  # route for onboarding slider DO NOT DELETE !
  get 'welcome', to:'pages#welcome', as: :welcome
  # route for onboarding questions DO NOT DELETE !
  get 'lifestyle', to: 'onboarding#lifestyle'
  # resources :onboarding, only: [:show] do
  resources :onboarding_questions, only: [:show]
  # route
  get 'click', to: 'onboarding_questions#click'

  resources :my_challenges, only: [:index, :show, :update]


  resources :fishes, only: [:index, :show] do
    resources :my_fishes, only: [:create]
  end

  resources :my_fishes, except: [:destroy, :create, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :challenges, except: [:index, :show]
    resources :fishes, except: [:index, :show]
  end
end

app/controllers/my_challenges_controller.rb
class MyChallengesController < ApplicationController

  def index
    if MyFish.where(alive: true, user_id: current_user.id).empty?
      redirect_to fishes_path
    end
    @challenges = Challenge.includes(:game_challenges)
    # Causing daily challenges to be empty
    # .where(game_challenges: { challenge_id: nil })
    @daily_challenges = @challenges.where(duration: "Daily")

    @my_ongoing_challenge = []
    my_ongoing_challenges = GameChallenge.where(status: "Ongoing")
    my_ongoing_challenges.each do |oc|
      @my_ongoing_challenge << oc if oc.my_fish.user == current_user
    end

    @my_last_ongoing_challenge = @my_ongoing_challenge.reverse.take(2)

    @my_complete_challenges = []
    my_completed_challenges = GameChallenge.where(status: "Completed")
    my_completed_challenges.each do |cc|
      @my_complete_challenges << cc if cc.my_fish.user == current_user
    end

    @my_last_complete_challenges = @my_complete_challenges.reverse.take(2)
    # @my_fish = MyFish.find_by(alive: true)
  end

  def ongoing
    @my_ongoing_challenge = []
    my_ongoing_challenges = GameChallenge.where(status: "Ongoing")
    my_ongoing_challenges.each do |oc|
      @my_ongoing_challenge << oc if oc.my_fish.user == current_user
    end
  end

  def completed
    @my_complete_challenges = []
    my_completed_challenges = GameChallenge.where(status: "Completed")
    my_completed_challenges.each do |cc|
      @my_complete_challenges << cc if cc.my_fish.user == current_user
    end
  end

  def show
    @my_challenge = GameChallenge.find(params[:id])
    @challenge = Challenge.find(@my_challenge.challenge_id)
    @progress = calculate_progress(@my_challenge)
    # MyChallenge.all.length == 10
    # Mychallenge.where(status: 'finished').length == 5
  end

  def create
    @my_challenge = GameChallenge.new(my_challenge_params)
    @my_challenge.my_fish = current_user.my_fishes.where(alive: true).first
    @my_challenge.start_time = DateTime.now
    @my_challenge.end_time = calculate_end_time(@my_challenge)
    @my_challenge.status = "Ongoing"
    my_fish = current_user.my_fishes.where(alive: true).first
    if @my_challenge.save
      current_user.score += (@my_challenge.challenge.score_health) / 2
      my_fish.score_health += (@my_challenge.challenge.score_health) / 2
      if my_fish.score_health > 100
        my_fish.score_health = 100
      end

      current_user.save!
      my_fish.save!
      redirect_to ongoing_challenge_path(@my_challenge.challenge_id)
    else
      redirect_to challenge_path(@my_challenge.challenge_id)
    end
  end

  def update
    @my_challenge = GameChallenge.find(params[:id])
    if @my_challenge.end_time.to_datetime > DateTime.now
      @my_challenge.status = "Abandoned"
      current_user.score -= (@my_challenge.challenge.score_health) / 2
      current_user.score = 0 if current_user.score.negative?
      my_fish = current_user.my_fishes.where(alive: true).first
      my_fish.score_health -= (@my_challenge.challenge.score_health) / 2
      my_fish.score_health = 0 if my_fish.score_health.negative?
      current_user.save!
      my_fish.save!
      @my_challenge.save!
      redirect_to my_challenges_path
    else
      @my_challenge.status = "Completed"
      current_user.save!
      current_user.my_fishes.first.save!
      @my_challenge.save!
      redirect_to completed_challenge_path(@my_challenge.challenge)
    end
  end

  private

  def my_challenge_params
    params.permit(:challenge_id)
  end

  def calculate_end_time(my_challenge)
    if my_challenge.challenge.duration == "Weekly"
      return @my_challenge.start_time + 604800
    else
      return @my_challenge.start_time + 2.628e+6
    end
  end

  def calculate_progress(my_challenge)
    today = DateTime.now.utc
    progress_helper_total =  my_challenge.end_time - my_challenge.start_time
    progress_helper_unique = today - my_challenge.start_time
    @progress = (progress_helper_unique / progress_helper_total)*100
    @progress.round(2)
  end


end

app/views/my_challenges/completed.html.erb
<%= render "shared/returnbar" %>
  <div class="container-fluid" >
  <h2 class="section-title">COMPLETED CHALLENGES</h2>
    <% @my_complete_challenges.each do |my_challenge| %>
      <div class="completed_challenge_card" >
        <%= my_challenge.challenge.name %>
        <p style="font-size: 12px">Completed on: <%= my_challenge.end_time.strftime('%m/%d/%Y') %></p>
      </div>
    <% end %>
  </div>

app/views/my_challenges/index.html.erb
<%= render "shared/returnbar" %>
<div class="container-fluid"  style="padding-bottom: 70px">
  <h1 class="main-title">CHALLENGES</h1>
  <h2 class="section-title">TODAY'S SELECTION</h2>

  <div class="scrolling-wrapper">

      <% @daily_challenges.each do |daily_challenge| %>
        <%= link_to challenge_path(daily_challenge.id) do %>
          <div class="challenge-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= daily_challenge.challenge_category.image %>)">
            <%= daily_challenge.name %>
          </div>
        <% end %>
      <% end %>
    </div>

  <h2 class="section-title">ONGOING CHALLENGES (<%= @my_ongoing_challenge.count %>)</h2>



      <% @my_last_ongoing_challenge.each do |my_challenge| %>
        <%= link_to my_challenge_path(my_challenge.id) do %>
          <div class="ongoing-challenge-card" style="url(<%= my_challenge.challenge.challenge_category.image %>)">
            #<%= my_challenge.challenge.name%>
            <p style="font-size: 12px"><%= my_challenge.start_time.strftime('%m/%d/%Y') %> - <%= my_challenge.end_time.strftime('%m/%d/%Y')  %></p>
              <% today = DateTime.now.utc
              progress_helper_total = my_challenge.end_time - my_challenge.start_time
              progress_helper_unique = today - my_challenge.start_time
              @progress = (progress_helper_unique / progress_helper_total)*100
              %>
              <div>
                  <div class="challenge-progress">
                    <div class="bar text-center " style="width: <%= @progress.round(2)%>%">
                     <!--  if we want the percentage to appear we can add it here -->
                    </div>
                  </div>
              </div>
            </div>
        <% end %>
      <% end %>

      <div class="btn-right">
        <%= link_to "See all >>", ongoing_challenges_path, class: "btn-all" %>
      </div>


  <h2 class="section-title">COMPLETED CHALLENGES (<%= @my_complete_challenges.count %>)</h2>


      <% @my_last_complete_challenges.each do |my_challenge| %>
        <div class="completed_challenge_card" >
        <%= my_challenge.challenge.name %>
        <p style="font-size: 12px">Completed on: <%= my_challenge.end_time.strftime('%m/%d/%Y') %></p>
        </div>
      <% end %>

      <div class="btn-right">
        <%= link_to "See all >>", completed_challenges_path, class: "btn-all" %>
      </div>

  <div class="centered-element">
    <%= link_to "Pick a new challenge", challenges_path, class: "btn-gradient" %>
  </div>



<% if MyFish.where(alive: true).count == 0 %>
<%= render "shared/msg_need_to_adopt_a_fish" %>
    <script>
      document.querySelector('.fish-modal').classList.toggle('show-modal')
    </script>
<% end %>

</div>
 <%= render "shared/navbar" %>

app/views/my_challenges/ongoing.html.erb
<%= render "shared/returnbar" %>
<div class="container-fluid" >
  <h2 class="section-title">ONGOING CHALLENGES</h2>
      <% @my_ongoing_challenge.each do |my_challenge| %>
        <%= link_to my_challenge_path(my_challenge.id) do %>
          <div class="ongoing-challenge-card" style="url(<%= my_challenge.challenge.challenge_category.image %>)">
            #<%= my_challenge.challenge.name%>
            <p style="font-size: 12px"><%= my_challenge.start_time.strftime('%m/%d/%Y') %> - <%= my_challenge.end_time.strftime('%m/%d/%Y')  %></p>
              <% today = DateTime.now.utc
              progress_helper_total = my_challenge.end_time - my_challenge.start_time
              progress_helper_unique = today - my_challenge.start_time
              @progress = (progress_helper_unique / progress_helper_total)*100
              %>
              <div>
                  <div class="challenge-progress">
                    <div class="bar text-center " style="width: <%= @progress.round(2)%>%">
                     <!--  if we want the percentage to appear we can add it here -->
                    </div>
                  </div>
              </div>
            </div>
        <% end %>
      <% end %>
</div>

app/views/my_challenges/show.html.erb
<%= render "shared/returnbar" %>
<div style="display: flex; flex-direction: column; justify-content: space-between; height: calc(100vh - 85px);">
  <div class="container-fluid">
    <h1 class="main-title"><%= @challenge.name.upcase %></h1>
    <p><%= @challenge.challenge_category.name %></p>
    <h2 class="section-title">DESCRIPTION</h2>
    <div>
      <%= @my_challenge.challenge.description %>
    </div>

    <div>
      <h2 class="section-title">SCORING</h2>
      <p>
        <% if @challenge.score_health != 0 %>
        <%= "Health points : #{@challenge.score_health}" %>
        <% else %>
        Health points : none
        <% end %>
      </p>
      <p>
        <% if @challenge.score_happiness != 0 %>
        <%= "Happiness points : #{@challenge.score_happiness}" %>
        <% else %>
        Happiness points : none
        <% end %>
      </p>
    </div>

    <div>
      <h2 class="section-title">STATUS</h2>
      <div>
        <div class="challenge-progress">
          <div class="bar text-center " style="width: <%= @progress.round(2)%>%">
            <!--  if we want the percentage to appear we can add it here -->
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="centered-element">
      <% if @my_challenge.end_time.to_datetime <= DateTime.now %>
      <%= link_to "Complete the challenge", my_challenge_path, method: :patch, class: "btn-blue"%>
      <% else %>
      <%= link_to "Stop the challenge", my_challenges_path, class: "btn-stop-challenges"%>
      <% end %>
    </div>
  </div>

</div>





<%= render "shared/msg_challenge_ending" %>
  <script>
    const button = document.querySelector(".btn-stop-challenges")
       button.addEventListener("click", function(e){
        e.preventDefault();
        document.querySelector('.fish-modal').classList.toggle('show-modal')
      });
    const buttonClose = document.querySelector(".btn-no")
       buttonClose.addEventListener("click", function(e){
        e.preventDefault();
        document.querySelector('.fish-modal').classList.toggle('show-modal')
      });
  </script>