config/routes.rb
Rails.application.routes.draw do

  get 'onboarding_question/show'
  devise_for :users, controllers: {registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks'}
  get 'profile', to: 'profile#show'
  get 'impact', to: 'impact#index'
  root to: 'my_fishes#show'

  # CHALLENGES

  resources :challenges, only: [:index, :show] do
    resources :my_challenges, only: [:create]
    resources :questions, only: [:show]
    member do
      get 'completed'
      get 'ongoing'
    end
  end

  get 'my_challenges/ongoing', to: 'my_challenges#ongoing', as: :ongoing_challenges
  get 'my_challenges/completed', to: 'my_challenges#completed', as: :completed_challenges

  #ONBOARDING
  # route for onboarding slider DO NOT DELETE !
  get 'welcome', to:'pages#welcome', as: :welcome
  # route for onboarding questions DO NOT DELETE !
  get 'lifestyle', to: 'onboarding#lifestyle'
  # resources :onboarding, only: [:show] do
  resources :onboarding_questions, only: [:show]
  # route
  get 'click', to: 'onboarding_questions#click'

  resources :my_challenges, only: [:index, :show, :update]


  resources :fishes, only: [:index, :show] do
    resources :my_fishes, only: [:create]
  end

  resources :my_fishes, except: [:destroy, :create, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :challenges, except: [:index, :show]
    resources :fishes, except: [:index, :show]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :content, :question_id, presence: true
  validates :status, inclusion: { in: [true, false] }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :challenge_category
  belongs_to :challenge_type
  has_many :questions
  has_many :game_challenges
  validates :min_score, :score_health, numericality: { only_integer: true }
  validates :score_happiness, numericality: true, inclusion: { in: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0] }
  validates :repeatable, inclusion: { in: [true, false] }
  validates :name, :min_score, :duration, :challenge_category_id, :description, :score_health, :score_happiness, presence: true
end

app/models/challenge_category.rb
class ChallengeCategory < ApplicationRecord
  has_many :challenges
  validates :name, presence: true
end

app/models/challenge_type.rb
class ChallengeType < ApplicationRecord
  has_many :challenges
  validates :name, presence: true
end

app/models/criteria_by_year.rb
class CriteriaByYear < ApplicationRecord
  belongs_to :fish
  belongs_to :global_criteria
end

app/models/critery_by_country.rb
class CriteryByCountry < ApplicationRecord
  belongs_to :fish
  belongs_to :regionalcriteria
end

app/models/endangered_status.rb
class EndangeredStatus < ApplicationRecord
  has_many :fish
  has_many :criteria_by_year
end

app/models/fish.rb
class Fish < ApplicationRecord
  has_many :my_fishes
  has_many :threats, through: :fish_threats
  has_many :criteria_by_country
  has_many :criteria_by_year
  validates :min_score, :max_age, numericality: { only_integer: true }
  validates :breed, :location, :endangered_status_id, :fish_avatar, :min_score, :max_age, :red_list_id, presence: true
end

app/models/fish_threat.rb
class FishThreat < ApplicationRecord
  belongs_to :fish
  belongs_to :threat
end

app/models/game_challenge.rb
class GameChallenge < ApplicationRecord
  belongs_to :my_fish
  belongs_to :challenge
  validates :my_fish_id, :challenge_id, :start_time, :end_time, :status, presence: true
end

app/models/level.rb
class Level < ApplicationRecord
  has_many :users
  validates :min_score, numericality: { only_integer: true }
  validates :name, :min_score, presence: true
end

app/models/my_fish.rb
# class GameFish < ApplicationRecord
class MyFish < ApplicationRecord
  belongs_to :user
  belongs_to :fish
  has_many :game_challenges, dependent: :destroy
  validates :score_happiness, numericality: true, inclusion: { in: [0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5] }
  validates :score_health, numericality: true, inclusion: { in: (0..100) }
  validates :user_id, :fish_id, :name, :start_date, :score_health, :score_happiness, presence: true

  after_create :initial_age

  def initial_age
    new_age = (Date.today - self.created_at.to_date).to_i + 1
    self.age = new_age
    self.save
  end

  def update_fish_stats
    new_age_helper = (Date.today - self.start_date.to_date).to_i
    if new_age_helper > self.age
      (new_age_helper - self.age).times do
        self.age += 1
        self.score_health -= 5 unless self.score_health == 0
        self.score_happiness -= 0.5 unless self.score_happiness == 0.0
        dead_or_alive
        break unless self.alive?
      end
    end
    self.save!
  end

  def death_probability
    death_probability = 100
    death_probability = death_probability - self.score_health
    death_probability = death_probability - (self.score_happiness * 9)
    return death_probability
  end

  def dead_or_alive
  self.alive = false if self.age >= self.fish.max_age
  self.alive = false if self.score_health <= 0
  self.alive = false if rand(200) < death_probability
  end
end

app/models/onboarding_answer.rb
class OnboardingAnswer < ApplicationRecord
  belongs_to :onboarding_question
end

app/models/onboarding_question.rb
class OnboardingQuestion < ApplicationRecord
  has_many :onboarding_answers
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :challenge
  has_many :answers
  validates :content, :challenge_id, presence: true
end

app/models/regional_criterium.rb
class RegionalCriterium < ApplicationRecord
  has_many :fish
  has_many :criteria_by_country
end

app/models/threat.rb
class Threat < ApplicationRecord
  has_many :fish_threats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :my_fishes
  has_many :game_challenges, through: :my_fishes
  validates :first_name, :last_name, presence: true
  devise :omniauthable, omniauth_providers: [:facebook]
  after_create :default_score, :default_level
  mount_uploader :avatar, PhotoUploader

  def default_score
    self.score = 0
    save
  end

  def default_level
    self.level_id = Level.find_by(min_score: 0).id
    save
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice("provider", "uid")
    user_params.merge! auth.info.slice("email", "first_name", "last_name")
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
  def never_started_challenges
    fishes_id = self.my_fishes.pluck(:id)
    played_games  = GameChallenge.where(my_fish_id: fishes_id).pluck(:challenge_id)
    Challenge.where.not(id: played_games)
  end

  def started_challenges_abandoned
    fishes_id = self.my_fishes.pluck(:id)
    played_games = GameChallenge.where(my_fish_id: fishes_id)
    played_games = played_games.where(status: "Abandoned").pluck(:challenge_id)
    Challenge.where(id: played_games)
  end

  def started_challenges_repeatable
    fishes_id = self.my_fishes.pluck(:id)
    played_games = GameChallenge.where(my_fish_id: fishes_id)
    played_games = played_games.where(status: "Completed").pluck(:challenge_id)
    Challenge.where(id: played_games)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Happy Fish</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <!-- <link rel="manifest" href="/manifest.json" /> -->
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link rel="apple-touch-icon" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
    <link rel="apple-touch-icon" sizes="167x167" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
    <link href="<%= image_path 'splashscreens/iphone5_splash.png' %>" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/iphone6_splash.png' %>" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/iphoneplus_splash.png' %>" media="(device-width: 621px) and (device-height: 1104px) and (-webkit-device-pixel-ratio: 3)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/iphonex_splash.png' %>" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/iphonexr_splash.png' %>" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/iphonexsmax_splash.png' %>" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/ipad_splash.png' %>" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/ipadpro1_splash.png' %>" media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/ipadpro3_splash.png' %>" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image" />
    <link href="<%= image_path 'splashscreens/ipadpro2_splash.png' %>" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)" rel="apple-touch-startup-image" />
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

    <%= render 'shared/flashes' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/welcome.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="false">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">

    <div class="carousel-item active">
      <div style="height: 100vh; background-color: white; display: flex; justify-content:center;">
        <div class= "welcome-container">

          <%= image_tag'tell.svg' %>

          <div>
            <h1 class="onboarding-title">TELL US</h1>
            <p class="onboarding-text">You want to make your share for the environment but you don’t know where to start ?</p>
            <p class="onboarding-text">tell us more about your lifestyle to assess how environmentally friendly it is </p>
          </div>

          <div>
            <p class="btn-pass">
              <%= link_to "Ignore intro", onboarding_question_path(OnboardingQuestion.all.first.id) %>
            </p>
          </div>

        </div>
      </div>
    </div>

    <div class="carousel-item ">
      <div style="height: 100vh; background-color: white; display: flex; justify-content:center;">
        <div class= "welcome-container">

          <%= image_tag'adopt.svg' %>

          <div>
            <h1 class="onboarding-title">ADOPT</h1>
            <p class="onboarding-text">adopt a fish !</p>
          </div>

          <div>
            <p class="btn-pass">
              <%= link_to "Ignore intro", onboarding_question_path(OnboardingQuestion.all.first.id) %>
            </p>
          </div>

        </div>
      </div>
    </div>

    <div class="carousel-item">
      <div style="height: 100vh; background-color: white; display: flex; justify-content:center;">
        <div  class= "welcome-container">

            <%= image_tag'play.svg' %>

          <div>
            <h1 class="onboarding-title">PLAY</h1>
            <p class="onboarding-text">Make your lifestyle greener by undertaking  concrete challenges that will make your fish happy & healthy !</p>
          </div>
          <div>
            <p class="btn-ok">
            <%= link_to "Ok let's play", onboarding_question_path(OnboardingQuestion.all.first.id) %>
            </p>
          </div>
        </div>
      </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" style="background: none !important" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" style="background: none !important" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_alert.html.erb
<div class="game-alert">
<p>Health: +
  <% if @challenge.duration == "Daily" %>
  <%= @my_challenge.challenge.score_health %>
  <% else %>
  <%= (@challenge.score_health) / 2  %>
  <% end %>
</p>
<% if @my_challenge.status == "Completed" %>
<p>Happiness: +
  <% @challenge.score_happiness.to_i.times do %>
  <i class="fas fa-star"></i>
  <% end %>
</p>
<% end %>
<p>User Score: +
  <% if @challenge.duration == "Daily" %>
  <%= @my_challenge.challenge.score_health %>
  <% else %>
  <%= (@challenge.score_health) / 2  %>
  <% end %>
</p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_msg_adoption_blocked.html.erb
<div class="fish-modal">
  <div class="fish-modal-content">
    <h1 class="modal-title">Hold your seahorses!</h1>
    <p>You can only take care of one fish at one time</p>
    <a class="next-q-btn btn-gradient centered" style="display: block;" href="/my_fishes/<%= @my_fish.id %>">What about <%= @my_fish.name %>?</a>
  </div>
</div>

app/views/shared/_msg_challenge_ending.html.erb
<div class="fish-modal">
  <div class="fish-modal-content">
    <h1 class="modal-title">Hold your seahorses!</h1>
    <p>Are you sure you want to stop this challenge? You will lose:</p>
    <p><strong>Health: - <%= (@my_challenge.challenge.score_health) / 2  %></strong>
    </p>
    <p><strong>User Score: -
      <%= (@my_challenge.challenge.score_health) / 2  %></strong>
    </p>
    <%= link_to "Yes", my_challenge_path(@my_challenge), method: :patch, class: "btn-yes" %>
    <%= link_to "No", my_challenge_path, class: "btn-no" %>
  </div>
</div>

app/views/shared/_msg_need_to_adopt_a_fish.html.erb
<div class="fish-modal">
  <div class="fish-modal-content">
    <h1 class="modal-title">Hold your seahorses!</h1>
      <p>You need to adopt a fish before you can begin a new challenge!</p>
    <a class="next-q-btn btn-gradient centered" style="display: block;" href="/fishes">Adopt a new fish!</a>
  </div>
</div>

app/views/shared/_msg_your_fish_died.html.erb
<div class="fish-modal">
  <div class="fish-modal-content">
    <h1 class="modal-title">R.I.P. <%= @my_fish.name %></h1>
    <% if @my_fish.age == @my_fish.fish.max_age %>
      <p>Your fish reached its maximum age and lived a fulfilling live</p>
    <% else %>
      <p>It's a sad day. Your fish died due to <%= ["Global Warming", "Pollution", "Overfishing"][rand(0..2)] %></p>
    <% end %>
    <a class="next-q-btn btn-gradient centered" style="display: block;" href="/fishes">Adopt a new fish!</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="footer-navbar d-flex justify-content-around align-items-center">
  <div class="nav-item">
    <% if MyFish.where(alive: true, user_id: current_user.id).empty? %>
      <%= link_to fishes_path , class: "#{ controller_name == "fishes" ? 'active-tab' : "inactive-tab" } yo d-flex justify-content-center align-items-center flex-column" do %>
      <i class="fas fa-fish"></i>
      <p class="nav-link-footer py-0">ADOPT</p>
      <% end %>
    <% else %>
      <%= link_to my_fish_path(@my_fish), class: "#{ controller_name == "my_fishes" ? 'active-tab' : "inactive-tab" } yo d-flex justify-content-center align-items-center flex-column" do %>
      <i class="fas fa-fish"></i>
      <p class="nav-link-footer py-0" style="font-weight: 700"; >MY FISH</p>
      <% end %>
    <% end %>
  </div>
  <div class="nav-item">
    <%= link_to my_challenges_path, class: "#{ controller_name == "my_challenges" ? 'active-tab' : "inactive-tab" } d-flex justify-content-center align-items-center flex-column" do %>
    <i class="fas fa-tasks"></i>
    <p class="nav-link-footer py-0" style="font-weight: 700;">CHALLENGES</p>
    <% end %>
  </div>
  <div class="nav-item">
    <%= link_to "/impact", class: "#{ controller_name == "impact" ? 'active-tab' : "inactive-tab" } d-flex justify-content-center align-items-center flex-column" do %>
    <i class="fas fa-tree"></i>
    <p class="nav-link-footer py-0" style="font-weight: 700;">IMPACT</p>
    <% end %>
  </div>
  <div class="nav-item">
    <%= link_to profile_path, class: "#{ controller_name == "profile" ? 'active-tab' : "inactive-tab" } d-flex justify-content-center align-items-center flex-column" do %>

      <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
      <% if current_user.facebook_picture_url %>
        <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu" %>
    <p class="nav-link-footer py-0" style="font-weight: 700;">PROFILE</p>
      <% elsif current_user.avatar %>
        <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu" %>
    <p class="nav-link-footer py-0" style="font-weight: 700;">PROFILE</p>
      <% else %>
    <i class="fas fa-user"></i>
    <p class="nav-link-footer py-0" style="font-weight: 700;">PROFILE</p>
      <% end %>

    <% end %>
  </div>
</div>

app/views/shared/_returnbar.html.erb
<div class="return-bar d-flex align-items-center">
  <div>
    <%= link_to request.referer.present? ? request.referer : root_path do %>
    <%= image_tag "blue-arrow.png", class: "blue-arrow-icon"%> Back
    <% end %>
  </div>
</div>