config/routes.rb
Rails.application.routes.draw do

  get 'onboarding_question/show'
  devise_for :users, controllers: {registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks'}
  get 'profile', to: 'profile#show'
  get 'impact', to: 'impact#index'
  root to: 'my_fishes#show'

  # CHALLENGES

  resources :challenges, only: [:index, :show] do
    resources :my_challenges, only: [:create]
    resources :questions, only: [:show]
    member do
      get 'completed'
      get 'ongoing'
    end
  end

  get 'my_challenges/ongoing', to: 'my_challenges#ongoing', as: :ongoing_challenges
  get 'my_challenges/completed', to: 'my_challenges#completed', as: :completed_challenges

  #ONBOARDING
  # route for onboarding slider DO NOT DELETE !
  get 'welcome', to:'pages#welcome', as: :welcome
  # route for onboarding questions DO NOT DELETE !
  get 'lifestyle', to: 'onboarding#lifestyle'
  # resources :onboarding, only: [:show] do
  resources :onboarding_questions, only: [:show]
  # route
  get 'click', to: 'onboarding_questions#click'

  resources :my_challenges, only: [:index, :show, :update]


  resources :fishes, only: [:index, :show] do
    resources :my_fishes, only: [:create]
  end

  resources :my_fishes, except: [:destroy, :create, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :challenges, except: [:index, :show]
    resources :fishes, except: [:index, :show]
  end
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :challenge_category
  belongs_to :challenge_type
  has_many :questions
  has_many :game_challenges
  validates :min_score, :score_health, numericality: { only_integer: true }
  validates :score_happiness, numericality: true, inclusion: { in: [0.0, 1.0, 2.0, 3.0, 4.0, 5.0] }
  validates :repeatable, inclusion: { in: [true, false] }
  validates :name, :min_score, :duration, :challenge_category_id, :description, :score_health, :score_happiness, presence: true
end

app/models/challenge_type.rb
class ChallengeType < ApplicationRecord
  has_many :challenges
  validates :name, presence: true
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  def index
    @challenges = current_user.never_started_challenges
    @daily_challenges = @challenges.where(duration: "Daily")
    @weekly_challenges = @challenges.where(duration: "Weekly")
    @monthly_challenges = @challenges.where(duration: "Monthly")
    @abandoned_challenges = current_user.started_challenges_abandoned
    @repeatable_challenges = current_user.started_challenges_repeatable.where(repeatable: true)
    @repeatable_challenges = @repeatable_challenges.uniq
    @abandoned_challenges = @abandoned_challenges.uniq
  end

  def show
    @challenge = Challenge.find(params[:id])
    @my_challenge = GameChallenge.new
  end

  def completed
    @challenge = Challenge.find(params[:id])
    my_fish = current_user.my_fishes.where(alive: true).first

    if @challenge.duration == "Daily"
      @my_challenge = GameChallenge.new
      @my_challenge.challenge = @challenge
      @my_challenge.my_fish = current_user.my_fishes.where(alive: true).first
      @my_challenge.start_time = DateTime.now
      @my_challenge.end_time = DateTime.now
      @my_challenge.status = "Completed"
      @my_challenge.save!
      current_user.score += (@my_challenge.challenge.score_health)
      my_fish.score_health += (@my_challenge.challenge.score_health)
    else
      current_user.score += (@challenge.score_health) / 2
      my_fish.score_health += (@challenge.score_health) / 2
    end
    current_user.save!
    my_fish.score_happiness += @challenge.score_happiness
    my_fish.score_happiness = 5.0 if my_fish.score_happiness > 5.0
    my_fish.score_health = 100 if my_fish.score_health > 100
    my_fish.save!
    @my_fish = my_fish.name
    @my_challenge = current_user.my_fishes.where(alive: true).first.game_challenges.where(challenge: @challenge).last
  end

  def ongoing
    @challenge = Challenge.find(params[:id])
    @my_fish = current_user.my_fishes.where(alive: true).first.name
    @my_challenge = current_user.my_fishes.where(alive: true).first.game_challenges.last
  end

  def onboarding_challenge
    # use params to get the score from each question
    # sum them
    # update current_score.score
  end

end

app/views/challenges/completed.html.erb
<div class="close-btn-container">
  <div class="close-button d-flex justify-content-center">
    <%= link_to my_fish_path do %>
    <p class="centered-element">X</p>
    <% end %>
  </div>
</div>


<div class="congrats-container">
  <div class="congrats-message-container">
    <div>
      <h1>Congratulations !</h1>
      <% if @challenge.score_health > 0 %>
      <p class="centered-element"> You won <%= @challenge.score_health %> health points in total for <%= @my_fish %> and made it happier ! </p>
      <% else %>
      <p class="centered-element"> You made <%= @my_fish %> happier ! </p>
      <% end %>
    </div>
  </div>
</div>

<%= render 'shared/alert' %>

<script>
  function moveIn() {
    var elem = document.querySelector('.game-alert')
    var pos = -180;
    var id = setInterval(frame, 0.5);
    function frame() {
      if (pos == 16) {
        clearInterval(id);
      } else {
        pos++;
        elem.style.right = pos + 'px';
      }
    }
  }

  function moveOut() {
    var elem = document.querySelector('.game-alert')
    var pos = 16;
    var id = setInterval(frame, 0.5);
    function frame() {
      if (pos == -200) {
        clearInterval(id);
      } else {
        pos--;
        elem.style.right = pos + 'px';
      }
    }
  }

setTimeout(function(){
  moveOut();
}, 4000);
moveIn();

</script>

app/views/challenges/index.html.erb
<div class="container-fluid">

  <h1 class="main-title">CHALLENGES</h1>

  <h2 class="section-title">ONE DAY</h2>

  <div class="scrolling-wrapper">

    <% @daily_challenges.each do |daily_challenge| %>

    <%= link_to challenge_path(daily_challenge.id) do %>
    <div class="challenge-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= daily_challenge.challenge_category.image %>)">
      <%= daily_challenge.name %>
    </div>
    <% end %>
    <% end %>
  </div>

  <h2 class="section-title">ONE WEEK</h2>

  <div class="scrolling-wrapper">
    <% @weekly_challenges.each do |weekly_challenge| %>
    <%= link_to challenge_path(weekly_challenge.id) do %>
    <div class="challenge-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= weekly_challenge.challenge_category.image %>)">
      <%= weekly_challenge.name %>
    </div>
    <% end %>
    <% end %>
  </div>

  <h2 class="section-title">ONE MONTH</h2>

  <div class="scrolling-wrapper">
    <% @monthly_challenges.each do |monthly_challenge| %>
    <%= link_to challenge_path(monthly_challenge.id) do %>
    <div class="challenge-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= monthly_challenge.challenge_category.image %>)">
      <%= monthly_challenge.name %>
    </div>
    <% end %>
    <% end %>
  </div>

  <h2 class="section-title">ANOTHER TRY?</h2>

  <div class="scrolling-wrapper">

    <% @abandoned_challenges.each do |daily_challenge| %>

    <%= link_to challenge_path(daily_challenge.id) do %>
    <div class="challenge-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= daily_challenge.challenge_category.image %>)">
      <%= daily_challenge.name %>
    </div>
    <% end %>
    <% end %>
  </div>

  <h2 class="section-title">REPETITION MAKES YOU A MASTER!</h2>

  <div class="scrolling-wrapper">

    <% @repeatable_challenges.each do |daily_challenge| %>

    <%= link_to challenge_path(daily_challenge.id) do %>
    <div class="challenge-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= daily_challenge.challenge_category.image %>)">
      <%= daily_challenge.name %>
    </div>
    <% end %>
    <% end %>
  </div>

</div>

<% if MyFish.where(alive: true).count == 0 %>
<%= render "shared/msg_need_to_adopt_a_fish" %>
    <script>
      document.querySelector('.fish-modal').classList.toggle('show-modal')
    </script>
<% end %>

<%= render 'shared/navbar' %>

app/views/challenges/onboarding_challenge.html.erb
<h1>Lifestyle</h1>
<p>How green is your Lifestyle?</p>


question:
1. 5
2. 10
3, 15
4. 20

auestion2

1. 5
2. 10
3, 15
4. 20

1. 5
2. 10
3, 15
4. 20

1. 5
2. 10
3, 15
4. 20


<div class="question-container">

  <div>
    <p class="question_label"><%= @question.content %></p>
  </div>

  <div>
    <fieldset class="form-group check_boxes answers">
      <% @answers.each do |answer| %>
         <div class="form-check answer" data-id="<%= answer.id %>">
            <input class="form-check-input check_boxes optional hidden-checkbox" type="checkbox" value="<%= answer.status %>" name="answer" id="<%= @challenge.name %>_answer_<%= answer.id %>">
            <label class="collection_check_boxes" for="<%= @challenge.name %>_answer_<%= answer.id %>"><%= answer.content %></label>
        </div>
      <% end %>
    </fieldset>
  </div>

  <div class="message">
    <p class="motivation_message centered"></p>
  </div>

  <div class="centered-element">
    <% if @last_question_id != @question.id %>
    <%= link_to "Next question", challenge_question_path(@challenge, @question.id + 1), class: "next-q-btn btn-gradient centered", style: "display: none"  %>
    <% else %>
    <%= link_to "Next", completed_challenge_path(@challenge.id), class: "next-q-btn btn-gradient centered", style: "display: none" %>
    <% end %>
  </div>

</div>

app/views/challenges/ongoing.html.erb
<div class="close-btn-container">
  <div class="close-button d-flex justify-content-center">
    <%= link_to my_fish_path do %>
    <p class="centered-element">X</p>
    <% end %>
  </div>
</div>


<div class="congrats-container">
  <div class="congrats-message-container">
    <div>
      <h1>Congratulations for starting a challenge!</h1>
      <p>Doing the first step is the most important, so you win already some points at this point!</p>
      <% if @challenge.score_health > 0 %>
      <p class="centered-element"> You won <%= @challenge.score_health / 2 %> health points for <%= @my_fish %> and made it happier ! </p>
      <% else %>
      <p class="centered-element"> You made <%= @my_fish %> happier ! </p>
      <% end %>
    </div>
  </div>
</div>

<%= render 'shared/alert' %>

<script>
  function moveIn() {
    var elem = document.querySelector('.game-alert')
    var pos = -180;
    var id = setInterval(frame, 0.5);
    function frame() {
      if (pos == 16) {
        clearInterval(id);
      } else {
        pos++;
        elem.style.right = pos + 'px';
      }
    }
  }

  function moveOut() {
    var elem = document.querySelector('.game-alert')
    var pos = 16;
    var id = setInterval(frame, 0.5);
    function frame() {
      if (pos == -200) {
        clearInterval(id);
      } else {
        pos--;
        elem.style.right = pos + 'px';
      }
    }
  }

setTimeout(function(){
  moveOut();
}, 4000);
moveIn();

</script>

app/views/challenges/show.html.erb
<%= render "shared/returnbar" %>
<div style="display: flex; flex-direction: column; justify-content: space-between; height: calc(100vh - 85px);">
<div class="container-fluid">
  <h1 class="main-title"><%= @challenge.name.upcase %></h1>
  <p><%= @challenge.challenge_category.name %></p>
  <h2 class="section-title">DESCRIPTION</h2>

  <div>
    <%= @challenge.description %>
  </div>
  <div>
    <h2 class="section-title">SCORING</h2>
    <p>
    <% if @challenge.score_health != 0 %>
    <%= "Health points : #{@challenge.score_health}" %>
    <% else %>
    Health points : none
    <% end %>
    </p>
    <p>
    <% if @challenge.score_happiness != 0 %>
    <%= "Happiness points : #{@challenge.score_happiness}" %>
    <% else %>
    Happiness points : none
    <% end %>
    </p>
  </div>
</div>
<div class="container-fluid">
  <div class ="d-flex flex-column centered-element">
    <div>
     <%= link_to "No thanks", challenges_path, class: "btn-blue" %>
    </div>
   <div>
    <% if   @challenge.challenge_type.name == "Quizz" %>
    <%= link_to " Let's do it!", challenge_question_path(@challenge.id,@challenge.questions.first.id), class: "btn-gradient"  %>
    <% elsif @challenge.duration == "Daily" %>
    <%= link_to "I have completed this!", completed_challenge_path(@challenge.id), class: "btn-gradient" %>
    <% else %>
    <%= link_to "Let's do it !", challenge_my_challenges_path(@challenge), method: :post, class: "btn-gradient"%>
    <% end %>
  </div>
</div>
</div>


<% if MyFish.where(alive: true).count == 0 %>
<%= render "shared/msg_need_to_adopt_a_fish" %>
<script>
  document.querySelector('.fish-modal').classList.toggle('show-modal')
</script>
<% end %>