config/routes.rb
Rails.application.routes.draw do

  get 'onboarding_question/show'
  devise_for :users, controllers: {registrations: 'users/registrations',  omniauth_callbacks: 'users/omniauth_callbacks'}
  get 'profile', to: 'profile#show'
  get 'impact', to: 'impact#index'
  root to: 'my_fishes#show'

  # CHALLENGES

  resources :challenges, only: [:index, :show] do
    resources :my_challenges, only: [:create]
    resources :questions, only: [:show]
    member do
      get 'completed'
      get 'ongoing'
    end
  end

  get 'my_challenges/ongoing', to: 'my_challenges#ongoing', as: :ongoing_challenges
  get 'my_challenges/completed', to: 'my_challenges#completed', as: :completed_challenges

  #ONBOARDING
  # route for onboarding slider DO NOT DELETE !
  get 'welcome', to:'pages#welcome', as: :welcome
  # route for onboarding questions DO NOT DELETE !
  get 'lifestyle', to: 'onboarding#lifestyle'
  # resources :onboarding, only: [:show] do
  resources :onboarding_questions, only: [:show]
  # route
  get 'click', to: 'onboarding_questions#click'

  resources :my_challenges, only: [:index, :show, :update]


  resources :fishes, only: [:index, :show] do
    resources :my_fishes, only: [:create]
  end

  resources :my_fishes, except: [:destroy, :create, :new]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :admin do
    resources :challenges, except: [:index, :show]
    resources :fishes, except: [:index, :show]
  end
end

app/models/fish.rb
class Fish < ApplicationRecord
  has_many :my_fishes
  has_many :threats, through: :fish_threats
  has_many :criteria_by_country
  has_many :criteria_by_year
  validates :min_score, :max_age, numericality: { only_integer: true }
  validates :breed, :location, :endangered_status_id, :fish_avatar, :min_score, :max_age, :red_list_id, presence: true
end

app/controllers/fishes_controller.rb
class FishesController < ApplicationController
  def index
    @fishes = Fish.all
    @user_score = current_user.score
    @available_fishes = Fish.where("min_score <= ?", @user_score)
    @blocked_fishes = Fish.where("min_score > ?", @user_score)
    @my_fish = MyFish.where(alive: true).where(user_id: current_user.id).first
  end

  def show
    @fish = Fish.find(params[:id])
    @my_fish = MyFish.new
  end

  # def count_adopted_fishes
  #   if MyFish.where(alive: true).count == 1
  #     render js: "document.querySelector('.modal').classList.toggle('show-modal')"
  #   end
  # end
end

app/views/fishes/index.html.erb
<div class="banner-container">
  <h1>Adoption</h1>
  <p>Step 1: pick a fish</p>
</div>


<div class="container-fluid">




    <h2 class="section-title">AVAILABLE FISH</h2>

    <div class="fish-grid">
      <% @available_fishes.each do |available_fish| %>
        <%= link_to fish_path(available_fish.id) do %>
          <div class="fish-index-card">
            <div class="fish-wrapper">
              <%= available_fish.breed %>
              <%= image_tag "myfish_#{available_fish.red_list_id}.svg", class: "fish-img" %>
            </div>

          </div>
        <% end %>
      <% end %>
    </div>

    <h2 class="section-title">LOCKED FISH</h2>

    <div class="fish-grid">
      <% @blocked_fishes.each do |blocked_fish| %>
          <div class="blocked-fish-index-card">
            <div class="fish-wrapper">
              <%= blocked_fish.breed %>
              <%= image_tag "myfish_#{blocked_fish.red_list_id}.svg", class: "fish-img" %>
            </div>
          </div>
      <% end %>
    </div>

</div>
<!--
how do I do to make the alert pop when I clic on  a blocked fish? -->

<div class="alert alert-warning blocked-fish alert-dismissible fade " role="alert">
  <span><strong>Oooops!</strong> It seems that your level does not allow you to adopt this fish</span>
  <a data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </a>
</div>

<script>
  const blockedFishes = document.querySelectorAll(".blocked-fish-index-card")
  const blockedFishAlert = document.querySelector(".blocked-fish")
  blockedFishes.forEach((fish) => {
    fish.addEventListener("click", (e) => {
      blockedFishAlert.classList.add("show")
    });
  })
</script>



<% if MyFish.where(alive: true).where(user_id: current_user.id).count == 1 %>
<%= render "shared/msg_adoption_blocked" %>
  <script>
    const fishes = document.querySelectorAll(".fish-index-card")
    fishes.forEach((fish) => {
      fish.addEventListener("click", (e) => {
        e.preventDefault();
        document.querySelector('.fish-modal').classList.toggle('show-modal')
      });
    })
  </script>
<% end %>

app/views/fishes/show.html.erb
<div class="fishes-container">

  <div class="banner-container text-center">
    <a><%= image_tag "arrow.png", class: "arrow-icon"%></a>
    <h1>Adoption</h1>
    <p>Step 2: Name your fish</p>
  </div>

  <div class="container">
    <div class="your-fish-title" style="color: #28C3D4"><h5>Your Fish</h5></div>
      <div class="fish-show-card card">
        <%= image_tag "myfish_#{@fish.red_list_id.to_s}.svg", class: "centered", width:"50%"%>
        <!-- myfish_#{@my_fish.fish.red_list_id.to_s}.svg -->
        <div class="fish-show-card-body">
          <div><p><strong style="font-weight: 700;">Species:</strong><br><%= @fish.breed %></p></div>
          <div><p><strong style="font-weight: 700;">Location:</strong><br><%= @fish.location %></p></div>
          <div><p><strong style="font-weight: 700;">Age:</strong><br>1 year old</p></div>
        </div>
      </div>


    <div id="your-fish-form">
        <%= simple_form_for [@fish, @my_fish] do |f| %>
          <%= f.input :name, label:"Fish Name"%>
          <div class="container">
            <%= f.button :submit, "Next", class: "btn-gradient" %>
          </div>

        <% end %>
      </div>




</div>